# Generated by Django 4.2.27 on 2026-02-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='postcode',
            new_name='location',
        ),
    ]
