# Generated by Django 5.1.6 on 2026-02-13 14:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_listing_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
