# Generated by Django 6.0.2 on 2026-02-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
