# Generated by Django 5.1.6 on 2026-02-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='registration_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
