# Generated by Django 5.1.6 on 2026-02-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_registration_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
